name: Auto Affiliate Blog Ultra Final PayPal
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install openai
      - run: python generate_post.py
      - name: Commit posts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase
          git add posts/
          git commit -m "Auto posts" || echo "No changes to commit"
          git push
